[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "task-tech-exposure"
version = "0.2.1"
description = "This package implements the methodology of 'Measuring Task-Level Technological Exposure: A Language Model Approach' (2026). It handles file download and management, data classification, and exposure measure generation."
readme = "README.md"
authors = [
    { name="Andre Mouton", email="moutona@wfu.edu" },
]
requires-python = ">=3.10"
dependencies = [
    "requests",
    "pandas",
    "numpy",
    "sentence_transformers>=3.3.0",
]
license = "MIT"
license-files = ["LICENSE.txt"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
train = [
    "openai>=1.0.0",
    "scikit-learn>=1.0",
    "statsmodels>=0.14",
    "datasets>=2.0",
]

[project.urls]
Repository = "https://github.com/armouton/task-tech-exposure"
